source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'spring', group: :development

gem 'haml', '~> 4.0.6'
gem 'haml-rails', '~> 0.8.2'

group :development, :test do
  gem 'rspec-rails', '~> 3.2.1'
end


